name: 'New Rule'
description: 'Propose a new lint rule'
title: 'Rule: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your rule proposal!

  - type: textarea
    id: description
    attributes:
      label: Rule description
      description: What does this rule check?
      placeholder: Checks that <section> elements contain a heading
    validations:
      required: true

  - type: textarea
    id: invalid-examples
    attributes:
      label: Invalid code examples
      description: Code that should trigger errors
      render: html
    validations:
      required: true

  - type: textarea
    id: valid-examples
    attributes:
      label: Valid code examples
      description: Code that should pass
      render: html
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links to specs, edge cases, etc.
    validations:
      required: false
